#spawn Categories(MONSTER, CREATURE, ... defaults..., custom pools from other mods
spawnCategories = ["MONSTER,85", "CREATURE,30", "AMBIENT,18", "AXOLOTLS,3", "UNDERGROUND_WATER_CREATURE,8", "WATER_CREATURE,15", "WATER_AMBIENT,24"]

