# Don't change this! Version used to track needed updates.
version = 0
enderPearlTrail = true
snowballTrailDensity = 0.2
allayMagicDensity = 0.2
vexMagicDensity = 0.2
sheepShearFluff = true
improvedDragonFireballTrail = true
commandBlockMinecartParticles = "ON"
endCrystalParticles = true
minecartLandingSparks = true
slimeTrails = true
magmaCubeTrails = true
replaceSlimeSquishParticles = true
replaceSpellCasterParticles = true
ironGolemCrackParticles = true
spectralArrowParticles = true
wardenDeathSoulParticles = true
xpBottleParticlesDisplayType = "VANILLA"
xpBottleParticlesDensity = 10

[attacked]
chickenFeathers = true
parrotFeathers = true
snowGolemSnowflakes = true

[sleeping]
playerSnoreChance = 0.0
playerSnoreSoundVolume = 1.0
playersHaveSleepingZs = true
villagerSnoreChance = 0.5
villagerSnoreSoundVolume = 0.4
villagersHaveSleepingZs = true
foxesHaveSleepingZs = true
batsHaveSleepingZs = true
catsHaveSleepingZs = true
otherMobsHaveSleepingZs = true
displaySleepingZsOnlyWhenSnoring = false
adjustNameTagWhenSleeping = true

[humanoids]
drowningBubbles = "DEFAULT"
drowningBubblesDensity = 10

[humanoids.frostyBreath]
displayType = "DEFAULT"
alpha = 0.2
waitTime = 60
seasons = "DEFAULT"
additionalBiomes = [  ]

[humanoids.player]
stomachGrowlingThreshold = 6
stomachGrowlingVolume = 1.0
heartBeatingThreshold = 6
heartbeatVolume = 0.0

[dustClouds]
scale = 1.0
alpha = 1.0
playerFell = true
playerRunning = true
playerRunningRequiresSpeed = true
mobFell = true
mobRunning = true
landMaceAttack = true
preventWhenRaining = true

[burning]
smoke = "DEFAULT"
flames = true
sparks = true
sounds = true

[itemRarity]
particlesDisplayType = "OFF"
particleColor = "NAME_COLOR"
mixedColorName = true
particleMaxHeight = 1.0
particleMaxSpeed = 1.0
particleDensity = 1.0

[explosives]
tntUpdateSmoke = true
tntFlames = true
tntSparks = true
creeperSmoke = "UPDATED"
creeperSparks = true